services:
  php-apache:
    build: .
    container_name: php_server
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
      - libretranslate
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=Rain
      - MYSQL_PASSWORD=Sunny
      - MYSQL_DB=News
      # Point TranslationService to our local LibreTranslate
      - LIBRE_TRANSLATE_URL=http://libretranslate:5000/translate

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: News
      MYSQL_USER: Rain
      MYSQL_PASSWORD: Sunny
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    restart: always
    ports:
      - "5000:5000"
    environment:
      - LT_LOAD_ONLY=en,ar,fr,es,de,zh,ja,ko,ru,it,pt,hi,tr,nl,sv,fa

volumes:
  db_data:
